stages:
- build
- test

jobs:
- name: build:prepare
  stage: build
  image: sunci/ruby:2.5.1
  script:
  - cp database-ci.yml config/database.yml
  - bundle _2.1.4_ install --path vendor/bundle
  cache:
  - key: vendor_$CI_BRANCH
    paths:
    - vendor/bundle

- name: test:rspec
  stage: test
  image: sunci/ruby:2.5.1
  services:
  - redis:alpine
  - image: postgres:12-alpine
    name: postgresql
    environment:
    - POSTGRES_DB=xxx
    - POSTGRES_USER=xxx
    - POSTGRES_PASSWORD=secret
  before_script:
  - bundle _2.1.4_ install --path vendor/bundle
  - mkdir .sun-ci
  script:
  - bundle _2.1.4_ exec rspec --format html --out .sun-ci/rspec.html spec/
  only:
    branches:
    - milestone1
  artifacts:
    name: rspec_report
    paths:
    - .sun-ci
    expires_in: 3 days

- name: test:bundle_audit
  stage: test
  image: sunci/ruby:2.5.1
  before_script:
  - bundle _2.1.4_ install --path vendor/bundle
  script:
  - bundle-audit check --update
  only:
    branches:
    - milestone1